# 🧱 Base Layer
FROM eclipse-temurin:17-jdk AS build
WORKDIR /app

# 🧰 Maven Wrapper
COPY .mvn/ .mvn/
COPY mvnw .
RUN chmod +x mvnw
COPY pom.xml .

# 📦 Dependencies (cached)
# So wird go-offline nur neu ausgeführt, wenn pom.xml sich ändert
RUN ./mvnw dependency:go-offline

# 🧑‍💻 Source & Resources
COPY src ./src
COPY src/main/resources/application.yml ./src/main/resources/
COPY src/main/resources/application-compose-dev.yml ./src/main/resources/

# Build
RUN ./mvnw clean package -DskipTests

# 🔒 Final Stage
FROM eclipse-temurin:17-jre-alpine
WORKDIR /app

# 🔒 Nicht-root Benutzer
RUN adduser -D -h /home/appuser appuser
USER appuser

# App Jar übernehmen
COPY --from=build /app/target/*.jar ./app.jar

ENTRYPOINT ["java", "-jar", "app.jar"]

# CMD ["java", "-jar", "app.jar", "--spring.profiles.active=compose-prod"]

#  docker build -t myimage:tasks-app .