# =====================================================================
# 🐳 Docker Compose – Dev Workflow (compose-dev)
# =====================================================================

# 🚀 Starten & Neu-Builden
# ------------------------
# docker compose -f docker-compose-dev.yml --env-file .env.compose-dev up --build
# docker compose up --build --detach
# docker compose ps -a

# 🛑 Stoppen & Aufräumen
# -----------------------
# docker compose -f docker-compose-dev.yml --env-file .env.compose-dev down -v
# docker compose down -v
# docker system prune -a

# 🧹 Volumes verwalten
# ---------------------
# docker volume ls
# docker volume inspect pgdata-dev
# docker volume rm pgdata-dev
# 🔄 Komplett neu starten (frisches Volume):
# docker compose down -v && docker volume rm pgdata-dev && docker compose up --build

# 📜 Logs & Debugging
# --------------------
# docker compose logs -f
# docker compose -f docker-compose-dev.yml logs -f app
# docker logs -f tasks-app
# docker ps -a   # alle Container (auch manuelle)

# 🗄️ Postgres – Zugriff & DB-Tools
# ---------------------------------
# docker exec -it postgres-dev sh
# docker exec -it postgres-dev psql -U admin -d tasks_dev_db
# \dt
# \d task_lists
# http://localhost:8080/actuator/health

# =====================================================================

services:
  db:
    image: ${DB_IMAGE}
    container_name: ${DB_CONTAINER}
    env_file:
      - .env.compose-dev
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      APP_DB_USER: ${APP_DB_USER}
      APP_DB_PASSWORD: ${APP_DB_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ${VOLUME}:/var/lib/postgresql # w. old version ${VOLUME}:/var/lib/postgresql/data
      - ./init-dev-db.sh:/docker-entrypoint-initdb.d/init-dev-db.sh
    ports:
      - "${DB_PORT:-5432}:5432"
  app:
    image: ${APP_IMAGE}
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: ${APP_CONTAINER}
    env_file:
      - .env.compose-dev
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    ports:
      - "${APP_PORT:-8080}:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata-dev:
