
deploy-minikube:
    kubectl create namespace dev --dry-run=client -o yaml | kubectl apply -f -
    kubectl apply -f k8s/init-db-script.yaml
    kubectl apply -f k8s/db-deployment.yaml
    kubectl apply -f k8s/db-service.yaml
    kubectl apply -f k8s/app-deployment.yaml
    kubectl apply -f k8s/app-service.yaml




