# 🛠️ Entwicklungsprofil: DEV

spring:
  # 🗄️ Datenbank-Konfiguration (H2 In-Memory)
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
    username: sa
    password: ""

  # 🧬 JPA & Hibernate
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  # 🧪 H2-Konsole
  h2:
    console:
      enabled: true
      path: /h2-console

  # 🚀 Startverhalten
  main:
    banner-mode: off

  # 🔄 Devtools (Live Reload)
  devtools:
    livereload:
      enabled: true

# 🐛 Logging
logging:
  level:
    org.thymeleaf: DEBUG
