# src/main/resources/application.yml
# 📦 App-Informationen & 🌍 Profil
spring:
  application:
    name: tasks
  output:
    ansi:
      enabled: ALWAYS
  profiles:
    default: local-dev # container-dev, local-dev
    #active: dev  # Optionen: dev, test oder prod

# 🧾 Versioning
application:
  version: 1.0.0

# 📋 Logging-Konfiguration
logging:
  interceptor:
    enabled: console  # Mögliche Werte: json oder console

# Swagger‑UI Operationen sortieren
springdoc:
  swagger-ui:
    tagsSorter:  alpha
    pathsSorter: none
    operationsSorter: method
#    operationsSorter: >
#      function(a, b) {
#        const order = {get: 1, post: 2, put: 3, patch: 4, delete: 5};
#        return order[a.get("method")] - order[b.get("method")];
#      }