spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${APP_DB_USER}
    password: ${APP_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
    # 🚫 H2-Konsole deaktiviert
    h2:
      console:
        enabled: false
  # 🚀 Startverhalten
  main:
    banner-mode: off
  # 🔄 Devtools (Live Reload)
  devtools:
    livereload:
      enabled: false

server:
  port: ${SERVER_PORT:8080}

# 📋 Logging
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE # SQL + Parameterbindung
  interceptor:
    enabled: console
