apiVersion: v1
kind: Service
metadata:
  name: tasks-service
  namespace: dev
spec:
  type: NodePort
  selector:
    app: tasks-app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
