# =====================================================================
# 🐳 Docker Compose – Dev Workflow (compose-dev)
# =====================================================================

# 🚀 Starten & Neu-Builden
# docker compose -f docker-compose-dev.yml --env-file .env.compose-dev up --build
# docker compose up --build --detach
# docker compose ps -a

# 🛑 Stoppen & Aufräumen
# docker compose -f docker-compose-dev.yml --env-file .env.compose-dev down -v
# docker compose down -v
# docker system prune -a

# 🧹 Volumes verwalten
# docker volume ls
# docker volume inspect ${VOLUME} docker volume inspect tasks_${VOLUME}, weil docker added prefix.
# docker volume rm ${VOLUME}
# docker compose down -v && docker volume rm ${VOLUME} && docker compose up --build

# 📜 Logs & Debugging
# docker compose logs -f
# docker compose -f docker-compose-dev.yml logs -f ${APP_CONTAINER}
# docker logs -f ${APP_CONTAINER}
# docker ps -a

# 🗄️ Postgres – Zugriff & DB-Tools
# docker exec -it ${DB_CONTAINER} sh
# docker exec -it ${DB_CONTAINER} psql -U ${POSTGRES_USER} -d ${DB_NAME}
# \dt
# \d task_lists
# http://localhost:${APP_PORT}/actuator/health

# =====================================================================

services:
  db:
    image: ${DB_IMAGE}
    container_name: ${DB_CONTAINER}
    env_file:
      - ../env/.env.compose-dev
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      APP_DB_USER: ${APP_DB_USER}
      APP_DB_PASSWORD: ${APP_DB_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ] # test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ${VOLUME}:/var/lib/postgresql
      - ./postgres/init-dev-db.sh:/docker-entrypoint-initdb.d/init-dev-db.sh
    ports:
      - "${DB_PORT:-5432}:5432"
  app:
    image: ${APP_NAME}:${APP_VERSION}
    build:
      context: ..
      dockerfile: ../Dockerfile.dev
    container_name: ${APP_CONTAINER}
    env_file:
      - ../env/.env.compose-dev
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    ports:
      - "${APP_PORT:-8080}:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata-dev:

# TODO ./mvnw -Dtest=TaskApiFullTestSuite test integrieren