# 📦 Docker-Kommandos für Setup & Wartung:
# ----------------------------------------
#
# docker compose -f ./compose/docker-compose-dev.yml --env-file ./compose/.env.compose-dev up --build
# docker compose -f ./compose/docker-compose-dev.yml --env-file ./compose/.env.compose-dev down -v
#
# 🔄 Projekt neu starten mit frischem Volume:
# docker compose down -v && docker volume rm pgdata && docker compose up --build

# 🧼 Nur Volume löschen:
# docker volume rm pgdata

# 🔍 Volume-Details anzeigen:
# docker volume inspect pgdata

# 🐙 Compose-Container anzeigen:
# docker compose ps -a

# 🐳 Alle Container anzeigen (auch manuelle):
# docker ps -a

# 🧠 Logs live verfolgen:
# docker compose logs -f

# 🚀 Compose im Hintergrund starten:
# docker compose up --build --detach

# 🧹 Container & Netzwerke komplett entfernen:
# docker system prune -a

services:
  db:
    image: postgres:alpine # ${DB_IMAGE}
    container_name: postgres-dev # ${DB_CONTAINER}
    env_file:
      - .env.compose-dev
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      APP_DB_USER: ${APP_DB_USER}
      APP_DB_PASSWORD: ${APP_DB_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ${VOLUME}:/var/lib/postgresql/data
      - ./init-dev-db.sh:/docker-entrypoint-initdb.d/init-dev-db.sh
    ports:
      - "${DB_PORT:-5432}:5432"
  app:
    image: tasks-app:last # ${APP_IMAGE}
    build:
      context: .
      dockerfile: ./compose/Dockerfile.dev
    container_name: tasks-app # ${APP_CONTAINER}
    env_file:
      - ./.env.compose-dev
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    ports:
      - "${APP_PORT:-8080}:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata-compose-dev: